# Generated by Django 4.1.1 on 2023-05-12 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conférence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=200)),
                ('capacite', models.IntegerField()),
                ('dateDebut', models.CharField(max_length=8)),
                ('dateFin', models.CharField(max_length=8)),
                ('startTime', models.CharField(max_length=200)),
                ('endTime', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('duree', models.IntegerField()),
                ('pays', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('imageConf', models.ImageField(default='conference/static/image/event.jpg', upload_to='conference/static/conferences/')),
                ('programme', models.FileField(upload_to='conference/static/conferences/')),
            ],
        ),
        migrations.CreateModel(
            name='Conférencier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=8)),
                ('bio', models.CharField(max_length=255)),
                ('image', models.ImageField(default='conference/static/image/user.png', upload_to='conference/static/conferenciers/')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=8)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.conférence')),
            ],
        ),
        migrations.AddField(
            model_name='conférence',
            name='conferencier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.conférencier'),
        ),
    ]
